name: Manter Render Acordado üí§üöÄ

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: "*/10 * * * *"
  workflow_dispatch:  # Permite rodar manualmente pelo bot√£o "Run workflow"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Pingar endpoint da aplica√ß√£o Render
        run: |
          echo "‚è∞ Enviando requisi√ß√£o para acordar o simulador..."
          curl -L -s -w "%{http_code}" -o /dev/null \
            "https://simulador-financiamento-ju90.onrender.com/api/financiamento/calcular?valorImovel=300000&entrada=50000&taxaJuros=1&prazo=360&tipo=PRICE"
          echo "‚úÖ Ping enviado ao endpoint da aplica√ß√£o."
